# Generated by Django 5.2.15 on 2026-06-18 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('openid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.IntegerField(default=10)),
                ('unionid', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('chart_json', models.TextField()),
                ('reading', models.TextField(blank=True, null=True)),
                ('ts', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='api.user')),
            ],
            options={
                'db_table': 'charts',
                'unique_together': {('user', 'fingerprint')},
            },
        ),
    ]
